name: WhatsApp Session

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Run WhatsApp session
        run: npm start

      # Wait until session files exist
      - name: Wait for session folder
        run: |
          while [ ! -d session/LocalAuth-main ]; do
            echo "‚è≥ Waiting for session folder..."
            sleep 1
          done

      - name: Commit session
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add session
          git commit -m "update whatsapp session $(date +%F)" || echo "No session changes"
          git push
